// Entire CLI plugin for OpenCode (V2).
//
// Originally auto-generated by `entire enable --agent opencode`. The generated
// file used the OpenCode 1 plugin API (a named `Plugin` export returning one
// hooks object), which OpenCode 2 rejects at load time:
//
//   Plugin must export a default definition with an id and an effect or setup
//   function. (cause: SchemaError(Missing key at ["default"]))
//
// This port keeps the same behavior on the OpenCode 2 API: a default export
// shaped { id, setup }. `setup` registers session hooks and subscribes to the
// public server event stream. Re-running `entire enable` overwrites this file
// with the V1 shape again; re-apply this port (or wait for upstream OpenCode 2
// support) until then.
//
// Uses node:child_process so hooks work under both Bun (OpenCode CLI/TUI)
// and Node (OpenCode Desktop's Electron sidecar). See #2014.
import { spawn, spawnSync } from "node:child_process"

export default {
  id: "entire",
  async setup(ctx) {
    const directory = ctx.location.directory

    // Track current session ID for events that don't carry one.
    let currentSessionID = null
    // Track the model used by the most recent model request.
    let currentModel = null
    // One-time model-context injection captured from the turn-start hook's
    // stdout, applied on the next model request via the session "context" hook.
    let pendingInjection = null
    // Sessions whose current turn already fired turn-end. V2 exposes several
    // terminal signals; this makes turn-end fire once per turn, and it resets
    // when the next turn starts.
    const turnEnded = new Set()

    /**
     * Build the shell command for a hook invocation.
     * Uses sh -c so the command is guarded by a `command -v` probe: when the
     * entire binary is not on PATH the hook exits 0 rather than failing the
     * surrounding OpenCode operation.
     */
    function hookCmd(hookName) {
      return ["sh", "-c", `if ! command -v entire >/dev/null 2>&1; then exit 0; fi; exec entire hooks opencode ${hookName}`]
    }

    /**
     * Pipe JSON payload to an entire hooks command (async).
     * Errors are logged but never thrown — plugin failures must not crash OpenCode.
     */
    async function callHook(hookName, payload) {
      try {
        const json = JSON.stringify(payload)
        const [cmd, ...args] = hookCmd(hookName)
        await new Promise((resolve) => {
          const proc = spawn(cmd, args, {
            cwd: directory,
            stdio: ["pipe", "ignore", "ignore"],
          })
          proc.on("error", () => resolve())
          proc.on("close", () => resolve())
          proc.stdin?.end(json + "\n")
        })
      } catch {
        // Silently ignore — plugin failures must not crash OpenCode
      }
    }

    /**
     * Synchronous variant for hooks that must complete before subsequent agent work
     * or process exit. `turn-start` must finish initializing session state before a
     * fast mid-turn commit can hit git hooks, and `turn-end` / `session-end` must
     * finish before `opencode run` tears down its event loop.
     */
    function callHookSync(hookName, payload) {
      try {
        const json = JSON.stringify(payload)
        const [cmd, ...args] = hookCmd(hookName)
        spawnSync(cmd, args, {
          cwd: directory,
          input: json + "\n",
          stdio: ["pipe", "ignore", "ignore"],
        })
      } catch {
        // Silently ignore — plugin failures must not crash OpenCode
      }
    }

    // parseInjectedContext scans a hook's stdout for Entire's injection envelope
    // ({"inject_context":"..."}) and returns the text to inject, or null.
    function parseInjectedContext(stdout) {
      if (!stdout) return null
      for (const line of stdout.split("\n")) {
        const trimmed = line.trim()
        if (!trimmed.startsWith("{")) continue
        try {
          const parsed = JSON.parse(trimmed)
          if (typeof parsed.inject_context === "string" && parsed.inject_context.length > 0) {
            return parsed.inject_context
          }
        } catch {
          // not our envelope — ignore
        }
      }
      return null
    }

    // fireTurnStart fires turn-start synchronously (state must be ready before
    // mid-turn commits) and stashes any model-context injection emitted on stdout
    // for the session "context" hook to apply. Entire emits the injection at most
    // once per session, so pendingInjection is set on the first turn only.
    function fireTurnStart(payload) {
      try {
        const json = JSON.stringify(payload)
        const [cmd, ...args] = hookCmd("turn-start")
        const proc = spawnSync(cmd, args, {
          cwd: directory,
          input: json + "\n",
          encoding: "utf8",
          stdio: ["pipe", "pipe", "ignore"],
        })
        const out = typeof proc.stdout === "string" ? proc.stdout : ""
        const injected = parseInjectedContext(out)
        if (injected) pendingInjection = injected
      } catch {
        // Silently ignore — plugin failures must not crash OpenCode
      }
    }

    function resetSessionTracking(sessionID) {
      if (currentSessionID === sessionID) return false
      currentModel = null
      currentSessionID = sessionID
      // Drop any turn-start injection captured for the prior session so it
      // can't leak into the new session's system prompt.
      pendingInjection = null
      turnEnded.clear()
      return true
    }

    function markTurnStart(sessionID) {
      if (sessionID) turnEnded.delete(sessionID)
    }

    function fireTurnEnd(sessionID) {
      const id = sessionID ?? currentSessionID
      if (!id) return
      if (turnEnded.has(id)) return
      turnEnded.add(id)
      // Use sync variant: `opencode run` exits on the same idle event, so an
      // async hook would be killed before completing.
      callHookSync("turn-end", {
        session_id: id,
        model: currentModel ?? "",
      })
    }

    // Apply the one-time Entire context injection captured at turn-start by
    // appending it to the system prompt for this model request, and track the
    // model the session is actually using.
    await ctx.session.hook("context", (event) => {
      if (event?.model?.id) currentModel = event.model.id
      if (pendingInjection && Array.isArray(event?.system)) {
        event.system.push({ type: "text", text: pendingInjection })
        pendingInjection = null
      }
    })

    // turn-start fires once per admitted user prompt. V2's prompt hook runs
    // during admission, so no message-id dedup is needed.
    await ctx.session.hook("prompt", (event) => {
      const sessionID = event?.sessionID
      if (!sessionID) return
      // Fallback: some run flows may not deliver session.created first, so
      // start the session here when the tracking reset reports a new session.
      if (resetSessionTracking(sessionID)) {
        callHookSync("session-start", { session_id: sessionID })
      }
      markTurnStart(sessionID)
      fireTurnStart({
        session_id: sessionID,
        prompt: event?.prompt?.text ?? "",
        model: currentModel ?? "",
      })
    })

    // Subscribe to the public server event stream for session lifecycle events.
    // V2 events carry their payload under `data` and carry a stable sessionID.
    const controller = new AbortController()
    void (async () => {
      try {
        for await (const event of ctx.event.subscribe({ signal: controller.signal })) {
          try {
            const type = event?.type
            const data = event?.data ?? {}
            const sessionID = data.sessionID ?? event?.sessionID ?? null
            switch (type) {
              case "session.created": {
                if (!sessionID) break
                if (resetSessionTracking(sessionID)) {
                  await callHook("session-start", { session_id: sessionID })
                }
                break
              }

              // A new turn's execution begins; arm turn-end for this turn.
              case "session.execution.started": {
                markTurnStart(sessionID)
                break
              }

              // Terminal signals. Dedupe so the first one per turn fires
              // turn-end exactly once.
              case "session.idle":
              case "session.execution.succeeded":
              case "session.execution.failed":
              case "session.execution.interrupted": {
                fireTurnEnd(sessionID)
                break
              }

              // session.status fires in both TUI and non-interactive (run) mode;
              // only its idle state ends a turn.
              case "session.status": {
                if (data?.status?.type !== "idle") break
                fireTurnEnd(sessionID)
                break
              }

              case "session.compacted": {
                if (!sessionID) break
                await callHook("compaction", { session_id: sessionID })
                break
              }

              case "session.deleted": {
                if (!sessionID) break
                if (currentSessionID === sessionID) currentSessionID = null
                turnEnded.delete(sessionID)
                // Use sync variant: session-end may fire during shutdown.
                callHookSync("session-end", { session_id: sessionID })
                break
              }
            }
          } catch {
            // Silently ignore — plugin failures must not crash OpenCode
          }
        }
      } catch {
        // Subscription aborted on shutdown — nothing to do.
      }
    })()

    // Cleanup runs when the plugin unloads (TUI close or `opencode run` exit).
    // session.deleted only fires on explicit user deletion, not on quit, so this
    // is the reliable way to end the active session on exit. Use the sync
    // variant: this is the last work before process exit.
    return () => {
      controller.abort()
      if (!currentSessionID) return
      const sessionID = currentSessionID
      currentSessionID = null
      pendingInjection = null
      callHookSync("session-end", { session_id: sessionID })
    }
  },
}
